name: Feature request
description: Suggest a feature
labels: ["enhancement"]
assignees:
  - rickaw
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem
    validations:
      required: false
    attributes:
      label: Is your feature request related to a problem? If so, please describe.
      description: A description of what the problem is
      placeholder: I'm always frustrated when ...
  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: Describe the solution you'd like
      description: A description of what you want to happen
      placeholder: When I press ... it should ...
  - type: textarea
    id: screenshots
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request

