name: Question
description: Ask a question to the team
labels: ["question"]
assignees:
  - Stuart-Knowles-SW
body:
  - type: textarea
    id: question
    validations:
      required: true
    attributes:
      label: What is your question?
      placeholder: How do I do ...?

