interface SnapletList {
    item_name: string;
    row_order: number;
    quantity_for_1?: string;
    notes_for_1?: string;
    quantity_for_2?: string;
    notes_for_2?: string;
    quantity_for_3?: string;
    notes_for_3?: string;
    quantity_for_4?: string;
    notes_for_4?: string;
    quantity_for_5?: string;
    notes_for_5?: string;
    quantity_for_6?: string;
    notes_for_6?: string;
    quantity_for_7?: string;
    notes_for_7?: string;
    quantity_for_8?: string;
    notes_for_8?: string;
    quantity_for_9?: string;
    notes_for_9?: string;
    quantity_for_10?: string;
    notes_for_10?: string;
}

interface SnapletListRequired {
    item_name: string;
    row_order: number;
    quantity_for_1: string | undefined;
    notes_for_1: string | null;
    quantity_for_2: string | undefined;
    notes_for_2: string | null;
    quantity_for_3: string | undefined;
    notes_for_3: string | null;
    quantity_for_4: string | undefined;
    notes_for_4: string | null;
    quantity_for_5: string | undefined;
    notes_for_5: string | null;
    quantity_for_6: string | undefined;
    notes_for_6: string | null;
    quantity_for_7: string | undefined;
    notes_for_7: string | null;
    quantity_for_8: string | undefined;
    notes_for_8: string | null;
    quantity_for_9: string | undefined;
    notes_for_9: string | null;
    quantity_for_10: string | undefined;
    notes_for_10: string | null;
}

const snapletListToRequired = (list: SnapletList): SnapletListRequired => {
    return {
        item_name: list.item_name,
        row_order: list.row_order,
        quantity_for_1: list.quantity_for_1 ?? undefined,
        notes_for_1: list.notes_for_1 ?? null,
        quantity_for_2: list.quantity_for_2 ?? undefined,
        notes_for_2: list.notes_for_2 ?? null,
        quantity_for_3: list.quantity_for_3 ?? undefined,
        notes_for_3: list.notes_for_3 ?? null,
        quantity_for_4: list.quantity_for_4 ?? undefined,
        notes_for_4: list.notes_for_4 ?? null,
        quantity_for_5: list.quantity_for_5 ?? undefined,
        notes_for_5: list.notes_for_5 ?? null,
        quantity_for_6: list.quantity_for_6 ?? undefined,
        notes_for_6: list.notes_for_6 ?? null,
        quantity_for_7: list.quantity_for_7 ?? undefined,
        notes_for_7: list.notes_for_7 ?? null,
        quantity_for_8: list.quantity_for_8 ?? undefined,
        notes_for_8: list.notes_for_8 ?? null,
        quantity_for_9: list.quantity_for_9 ?? undefined,
        notes_for_9: list.notes_for_9 ?? null,
        quantity_for_10: list.quantity_for_10 ?? undefined,
        notes_for_10: list.notes_for_10 ?? null,
    };
};

const listsSeed: SnapletList[] = [
    {
        item_name: "Fresh Fruit / Vegetables",
        row_order: 1,
        quantity_for_1: "Mixture",
        quantity_for_2: "Mixture",
        quantity_for_3: "Mixture",
        quantity_for_4: "Mixture",
        quantity_for_5: "Mixture",
        quantity_for_6: "Mixture",
        quantity_for_7: "Mixture",
        quantity_for_8: "Mixture",
        quantity_for_9: "Mixture",
        quantity_for_10: "Mixture",
    },

    {
        item_name: "Eggs",
        row_order: 2,
        quantity_for_1: "4",
        notes_for_1:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_2: "6",
        notes_for_2:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_3: "6",
        notes_for_3:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_4: "6",
        notes_for_4:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_5: "6",
        notes_for_5:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_6: "6",
        notes_for_6:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_7: "10",
        notes_for_7:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_8: "10",
        notes_for_8:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_9: "12",
        notes_for_9:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantity_for_10: "12",
        notes_for_10:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
    },

    {
        item_name: "Washing Up Liquid",
        row_order: 3,
        quantity_for_1: "1 decanted",
        notes_for_1: "Please only use decanted rather than full",
        quantity_for_2: "1 decanted",
        notes_for_2: "Please only use decanted rather than full",
        quantity_for_3: "1",
        quantity_for_4: "1",
        quantity_for_5: "1",
        quantity_for_6: "1",
        quantity_for_7: "1",
        quantity_for_8: "1",
        quantity_for_9: "1",
        quantity_for_10: "1",
    },

    {
        item_name: "Laundry Pods",
        row_order: 4,
        quantity_for_1: "1 bag of 2 pods",
        quantity_for_2: "1 bag of 4 pods",
        quantity_for_3: "1 bag of 4 pods",
        quantity_for_4: "6 pods",
        notes_for_4: "1 bag of 4 & 1 bag of 2",
        quantity_for_5: "6 pods",
        notes_for_5: "1 bag of 4 & 1 bag of 2",
        quantity_for_6: "8 pods",
        notes_for_6: "2 bags of 4 pods",
        quantity_for_7: "8 pods",
        notes_for_7: "2 bags of 4 pods",
        quantity_for_8: "8 pods",
        notes_for_8: "2 bags of 4 pods",
        quantity_for_9: "8 pods",
        notes_for_9: "2 bags of 4 pods",
        quantity_for_10: "8 pods",
        notes_for_10: "2 bags of 4 pods",
    },

    {
        item_name: "Nappies and Baby Wipes",
        row_order: 5,
        quantity_for_2: "As Required",
        notes_for_2: "Please ask if unsure",
        quantity_for_3: "As Required",
        notes_for_3: "Please ask if unsure",
        quantity_for_4: "As Required",
        notes_for_4: "Please ask if unsure",
        quantity_for_5: "As Required",
        notes_for_5: "Please ask if unsure",
        quantity_for_6: "As Required",
        notes_for_6: "Please ask if unsure",
        quantity_for_7: "As Required",
        notes_for_7: "Please ask if unsure",
        quantity_for_8: "As Required",
        notes_for_8: "Please ask if unsure",
        quantity_for_9: "As Required",
        notes_for_9: "Please ask if unsure",
        quantity_for_10: "As Required",
        notes_for_10: "Please ask if unsure",
    },

    {
        item_name: "Oats",
        row_order: 6,
        quantity_for_2: "1 bag",
        quantity_for_3: "1 bag",
        quantity_for_4: "1 bag",
        quantity_for_5: "1 bag",
        quantity_for_6: "1 bag",
        quantity_for_7: "1 bag",
        quantity_for_8: "1 bag",
        quantity_for_9: "1 bag",
        quantity_for_10: "1 bag",
    },

    {
        item_name: "Bread",
        row_order: 7,
        quantity_for_1: "1",
        notes_for_1: "Not always in stock",
        quantity_for_2: "1",
        notes_for_2: "Not always in stock",
        quantity_for_3: "1",
        notes_for_3: "Not always in stock",
        quantity_for_4: "2",
        notes_for_4: "Not always in stock",
        quantity_for_5: "2",
        notes_for_5: "Not always in stock",
        quantity_for_6: "2",
        notes_for_6: "Not always in stock",
        quantity_for_7: "3",
        notes_for_7: "Not always in stock",
        quantity_for_8: "3",
        notes_for_8: "Not always in stock",
        quantity_for_9: "3",
        notes_for_9: "Not always in stock",
        quantity_for_10: "3",
        notes_for_10: "Not always in stock",
    },

    {
        item_name: "Pet Food Box (only if requested)",
        row_order: 8,
        quantity_for_1: "pre-made box",
        quantity_for_2: "pre-made box",
        quantity_for_3: "pre-made box",
        quantity_for_4: "pre-made box",
        quantity_for_5: "pre-made box",
        quantity_for_6: "pre-made box",
        quantity_for_7: "pre-made box",
        quantity_for_8: "pre-made box",
        quantity_for_9: "pre-made box",
        quantity_for_10: "pre-made box",
    },

    {
        item_name: "Cereal",
        row_order: 9,
        quantity_for_1: "3 sachets or small box or 1 sleeve weetabix",
        quantity_for_2: "1 small cereal",
        quantity_for_3: "1 medium /large cereal",
        quantity_for_4: "2 Medium boxes cereal",
        quantity_for_5: "2 medium boxes cereal",
        quantity_for_6: "1 large and 1 small cereal",
        quantity_for_7: "1 large and 1 small cereal",
        quantity_for_8: "2 large boxes cereals",
        quantity_for_9: "2 large boxes cereal",
        quantity_for_10: "2 large boxes cereal include one supersize if around.",
    },

    {
        item_name: "Tea / Coffee",
        row_order: 10,
        quantity_for_1: "40 teabags/small jar",
        notes_for_1: "if neither listed, give tea",
        quantity_for_2: "80 teabags/small jar",
        notes_for_2: "if neither listed, give tea",
        quantity_for_3: "80 teabags/small jar",
        notes_for_3: "if neither listed, give tea",
        quantity_for_4: "80 teabags/medium jar",
        notes_for_4: "if neither listed, give tea",
        quantity_for_5: "80 teabags/medium jar",
        notes_for_5: "if neither listed, give tea",
        quantity_for_6: "80 teabags/medium jar",
        notes_for_6: "if neither listed, give tea",
        quantity_for_7: "80 teabags/large jar",
        notes_for_7: "if neither listed, give tea",
        quantity_for_8: "120 teabags/large jar",
        notes_for_8: "if neither listed, give tea",
        quantity_for_9: "120 teabags/large jar",
        notes_for_9: "if neither listed, give tea",
        quantity_for_10: "120 teabags/large jar",
        notes_for_10: "if neither listed, give tea",
    },

    {
        item_name: "Milk",
        row_order: 11,
        quantity_for_1: "1 Litre",
        notes_for_1: "skimmed",
        quantity_for_2: "1 Litre",
        notes_for_2: "1 full fat",
        quantity_for_3: "2",
        notes_for_3: "1 Whole if Child",
        quantity_for_4: "2",
        notes_for_4: "1 Whole if Child",
        quantity_for_5: "2",
        notes_for_5: "1 Whole if Child",
        quantity_for_6: "3",
        notes_for_6: "2 full fat or skimmed",
        quantity_for_7: "3",
        notes_for_7: "2 full fat or skimmed",
        quantity_for_8: "3",
        notes_for_8: "2 full fat or skimmed",
        quantity_for_9: "4",
        notes_for_9: "3 full fat or skimmed",
        quantity_for_10: "4",
        notes_for_10: "3 full fat or skimmed",
    },

    {
        item_name: "Drinks (inc Fruit Juice)",
        row_order: 12,
        quantity_for_1: "2 small cartons/tins",
        notes_for_1: "1 litre fruit juice",
        quantity_for_2: "1",
        notes_for_2: "1 litre fruit juice",
        quantity_for_3: "1",
        notes_for_3: "1 litre fruit juice",
        quantity_for_4: "1",
        notes_for_4: "1 litre fruit juice",
        quantity_for_5: "1",
        notes_for_5: "1 litre fruit juice",
        quantity_for_6: "1",
        notes_for_6: "Fruit Juice",
        quantity_for_7: "2",
        notes_for_7: "Fruit Juice",
        quantity_for_8: "2",
        notes_for_8: "Fruit Juice",
        quantity_for_9: "2",
        notes_for_9: "Fruit Juice",
        quantity_for_10: "2",
        notes_for_10: "Fruit Juice",
    },

    {
        item_name: "Squash",
        row_order: 13,
        quantity_for_5: "1",
        notes_for_5: "1 standard bottle (if no squash use fruit juice)",
        quantity_for_6: "1",
        notes_for_6: "1 standard bottle (if no squash use fruit juice)",
        quantity_for_7: "1",
        notes_for_7: "1 standard bottle (if no squash use fruit juice)",
        quantity_for_8: "1",
        notes_for_8: "1 large bottle (if no squash use fruit juice)",
        quantity_for_9: "1",
        notes_for_9: "1 large bottle (if no squash use fruit juice)",
        quantity_for_10: "1",
        notes_for_10: "1 large bottle (if no squash use fruit juice)",
    },

    {
        item_name: "Soup - extra being added due to cold weather",
        row_order: 14,
        quantity_for_1: "2",
        notes_for_1: "Please don't divide cuppa soup boxes -- 1 box = 1 tin",
        quantity_for_2: "4",
        quantity_for_3: "6",
        quantity_for_4: "8",
        quantity_for_5: "8",
        quantity_for_6: "8",
        quantity_for_7: "8",
        quantity_for_8: "10",
        quantity_for_9: "10",
        quantity_for_10: "10",
    },

    {
        item_name: "Other Tinned Vegetables - everyone to have carrots",
        row_order: 15,
        quantity_for_1: "2",
        notes_for_1: "use small tins if possible",
        quantity_for_2: "2",
        quantity_for_3: "3",
        notes_for_3: "2 carrots",
        quantity_for_4: "3",
        notes_for_4: "2 carrots",
        quantity_for_5: "3",
        notes_for_5: "2 carrots",
        quantity_for_6: "4",
        notes_for_6: "3 carrots",
        quantity_for_7: "4",
        notes_for_7: "3 carrots",
        quantity_for_8: "4",
        notes_for_8: "3 carrots",
        quantity_for_9: "5",
        notes_for_9: "3 carrots",
        quantity_for_10: "5",
        notes_for_10: "3 carrots",
    },

    {
        item_name: "Pulses",
        row_order: 16,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "2",
        quantity_for_4: "4",
        quantity_for_5: "4",
        quantity_for_6: "4",
        quantity_for_7: "4",
        quantity_for_8: "4",
        quantity_for_9: "4",
        quantity_for_10: "4",
    },

    {
        item_name: "Dried Pulses",
        row_order: 17,
        quantity_for_5: "1 bag",
        quantity_for_6: "1 bag",
        quantity_for_7: "1 bag",
        quantity_for_8: "1 bag",
        quantity_for_9: "1 bag",
        quantity_for_10: "1 bag",
    },

    {
        item_name: "Baked Beans / Tinned Spaghetti for Children",
        row_order: 18,
        quantity_for_1: "1",
        quantity_for_2: "2",
        quantity_for_3: "3",
        quantity_for_4: "4",
        quantity_for_5: "5",
        quantity_for_6: "6",
        quantity_for_7: "7",
        quantity_for_8: "8",
        quantity_for_9: "9",
        quantity_for_10: "10",
    },

    {
        item_name: "Tinned Tomatoes",
        row_order: 19,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "2",
        quantity_for_4: "2",
        quantity_for_5: "2",
        quantity_for_6: "3",
        quantity_for_7: "3",
        quantity_for_8: "3",
        quantity_for_9: "3",
        quantity_for_10: "3",
    },

    {
        item_name: "Meat - If eat pork please include at least 50% pork based.",
        row_order: 20,
        quantity_for_1: "3",
        notes_for_1: "mix",
        quantity_for_2: "3",
        notes_for_2: "mix",
        quantity_for_3: "4",
        notes_for_3: "Mixture",
        quantity_for_4: "5",
        notes_for_4: "Mixture",
        quantity_for_5: "6",
        notes_for_5: "Mixture",
        quantity_for_6: "6",
        notes_for_6: "Mixture",
        quantity_for_7: "7",
        notes_for_7: "Mixture",
        quantity_for_8: "7",
        notes_for_8: "Mixture",
        quantity_for_9: "8",
        notes_for_9: "Mixture",
        quantity_for_10: "8",
        notes_for_10: "Mixture",
    },

    {
        item_name: "Fish",
        row_order: 21,
        quantity_for_1: "2",
        quantity_for_2: "3",
        quantity_for_3: "3",
        quantity_for_4: "4",
        quantity_for_5: "4",
        quantity_for_6: "5",
        quantity_for_7: "5",
        quantity_for_8: "6",
        quantity_for_9: "6",
        quantity_for_10: "7",
    },

    {
        item_name: "Vegetarian Meal",
        row_order: 22,
        quantity_for_1: "1",
        notes_for_1: "If client is veggie",
        quantity_for_2: "2",
        notes_for_2: "If client is veggie",
        quantity_for_3: "2",
        notes_for_3: "If client is veggie",
        quantity_for_4: "3",
        notes_for_4: "If client is veggie",
        quantity_for_5: "4",
        notes_for_5: "If client is veggie",
        quantity_for_6: "5",
        notes_for_6: "If client is veggie",
        quantity_for_7: "5",
        notes_for_7: "If client is veggie",
        quantity_for_8: "6",
        notes_for_8: "If client is veggie",
        quantity_for_9: "6",
        notes_for_9: "If client is veggie",
        quantity_for_10: "6",
        notes_for_10: "If client is veggie",
    },

    {
        item_name: "Cooking Sauce",
        row_order: 23,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "1",
        quantity_for_4: "2",
        quantity_for_5: "2",
        quantity_for_6: "2",
        quantity_for_7: "2",
        quantity_for_8: "3",
        quantity_for_9: "3",
        quantity_for_10: "3",
    },

    {
        item_name: "Potatoes",
        row_order: 24,
        quantity_for_1: "1",
        notes_for_1: "Small tin or dried mash",
        quantity_for_2: "1",
        notes_for_2: "Big tin or dried mash",
        quantity_for_3: "2",
        notes_for_3: "Big tin and/or dried mash",
        quantity_for_4: "2",
        notes_for_4: "Big tin and/or dried mash",
        quantity_for_5: "3",
        quantity_for_6: "4",
        quantity_for_7: "4",
        quantity_for_8: "4",
        quantity_for_9: "4",
        quantity_for_10: "4",
    },

    {
        item_name: "Savoury Snacks",
        row_order: 25,
        quantity_for_1: "1",
        quantity_for_2: "2",
        quantity_for_3: "2",
        quantity_for_4: "2",
        quantity_for_5: "3",
        quantity_for_6: "3",
        quantity_for_7: "4",
        quantity_for_8: "4",
        quantity_for_9: "4",
        quantity_for_10: "4",
    },

    {
        item_name: "Custard",
        row_order: 26,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "1",
        quantity_for_4: "1",
        quantity_for_5: "2",
        quantity_for_6: "2",
        quantity_for_7: "2",
        quantity_for_8: "2",
        quantity_for_9: "2",
        quantity_for_10: "2",
    },

    {
        item_name: "Oil - Families Only",
        row_order: 27,
        quantity_for_4: "1",
        quantity_for_5: "1",
        quantity_for_6: "1",
        quantity_for_7: "1",
        quantity_for_8: "1",
        quantity_for_9: "1",
        quantity_for_10: "1",
    },

    {
        item_name: "Pasta",
        row_order: 28,
        quantity_for_1: "1kg",
        quantity_for_2: "1.5kg",
        quantity_for_3: "2kg",
        quantity_for_4: "2.5kg",
        quantity_for_5: "2.5kg",
        quantity_for_6: "2.5kg",
        quantity_for_7: "3kg",
        quantity_for_8: "3kg",
        quantity_for_9: "3kg",
        quantity_for_10: "4kg",
    },

    {
        item_name: "Rice",
        row_order: 29,
        quantity_for_1: "1 Instant Rice Pouch",
        notes_for_1: "or 1 small 500g bag",
        quantity_for_2: "1kg",
        notes_for_2:
            "Only if request in dietary info - please do not use 500 grm rice these are for singles only.",
        quantity_for_3: "1kg",
        notes_for_3: "Only if request in dietary info - please do not use 500grm rice bags",
        quantity_for_4: "1kg",
        notes_for_4: "Only if request in dietary info - please do not use 500grm rice bags",
        quantity_for_5: "1kg",
        notes_for_5: "Only if request in dietary info - please do not use 500grm rice bags",
        quantity_for_6: "1kg",
        notes_for_6:
            "Only if requested in dietary info, use big bag if available Please do not use 500grm bags",
        quantity_for_7: "2kg",
        notes_for_7: "Only if requested in dietary info, Please do not use 500 grm bags",
        quantity_for_8: "2kg",
        notes_for_8: "Only if requested in dietary info, Please do not use 500 grm bags",
        quantity_for_9: "2kg plus",
        notes_for_9: "Only if requested in dietary info, use big bag if available",
        quantity_for_10: "2kg plus",
        notes_for_10: "Only if requested in dietary info, use big bag if available",
    },

    {
        item_name: "Instant Noodles / Pasta for those with no cooking facilities",
        row_order: 30,
        quantity_for_1: "2",
        notes_for_1: "Only if no cooking facilities",
    },

    {
        item_name: "Rice Pudding",
        row_order: 31,
        quantity_for_4: "1",
        quantity_for_5: "2",
        quantity_for_6: "2",
        quantity_for_7: "2",
        quantity_for_8: "2",
        quantity_for_9: "2",
        quantity_for_10: "2",
    },

    {
        item_name: "Other Pudding",
        row_order: 32,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "1",
        quantity_for_4: "1",
        quantity_for_5: "1",
        quantity_for_6: "1",
        quantity_for_7: "1",
        quantity_for_8: "1",
        quantity_for_9: "1",
        quantity_for_10: "1",
    },

    {
        item_name: "Jam / Honey / Peanut Butter (Preserves)",
        row_order: 33,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "1",
        quantity_for_4: "1",
        quantity_for_5: "1",
        quantity_for_6: "1",
        quantity_for_7: "1",
        quantity_for_8: "1",
        quantity_for_9: "2",
        quantity_for_10: "2",
    },

    {
        item_name: "Tinned Fruit",
        row_order: 34,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "2",
        notes_for_3: "If very large tins please cut back",
        quantity_for_4: "2",
        notes_for_4: "If very large tins please cut back",
        quantity_for_5: "3",
        notes_for_5: "If very large tins please cut back",
        quantity_for_6: "3",
        notes_for_6: "If very large tins please cut back",
        quantity_for_7: "3",
        notes_for_7: "If very large tins please cut back",
        quantity_for_8: "4",
        notes_for_8: "If very large tins please cut back",
        quantity_for_9: "4",
        notes_for_9: "If very large tins please cut back",
        quantity_for_10: "4",
        notes_for_10: "If very large tins please cut back",
    },

    {
        item_name: "Cereal bars",
        row_order: 35,
        quantity_for_1: "1",
        quantity_for_2: "2",
        quantity_for_3: "3",
        quantity_for_4: "4",
        quantity_for_5: "5",
        quantity_for_6: "6",
        quantity_for_7: "7",
        quantity_for_8: "8",
        quantity_for_9: "9",
        quantity_for_10: "10",
    },

    {
        item_name: "Chocolate",
        row_order: 36,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "1",
        quantity_for_4: "1",
        quantity_for_5: "2",
        quantity_for_6: "2",
        quantity_for_7: "2",
        quantity_for_8: "2",
        quantity_for_9: "2",
        quantity_for_10: "2",
    },

    {
        item_name: "Biscuits",
        row_order: 37,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "2",
        quantity_for_4: "2",
        quantity_for_5: "2",
        quantity_for_6: "3",
        quantity_for_7: "3",
        quantity_for_8: "3",
        quantity_for_9: "4",
        quantity_for_10: "4",
    },

    {
        item_name: "Sanitary Pads",
        row_order: 38,
        quantity_for_2: "1 pack per person",
        notes_for_2: "as required. Add panty liners as well.",
        quantity_for_3: "1 pack per person",
        notes_for_3: "as required. Add panty liners as well.",
        quantity_for_4: "1 pack per person",
        notes_for_4: "as required. Add panty liners as well.",
        quantity_for_5: "1 pack per person",
        notes_for_5: "as required. Add panty liners as well.",
        quantity_for_6: "1 pack per person",
        notes_for_6: "as required. Add panty liners as well.",
        quantity_for_7: "1 pack per person",
        notes_for_7: "as required. Add panty liners as well.",
        quantity_for_8: "1 pack per person",
        notes_for_8: "as required. Add panty liners as well.",
        quantity_for_9: "1 pack per person",
        notes_for_9: "as required. Add panty liners as well.",
        quantity_for_10: "1 pack per person",
        notes_for_10: "as required. Add panty liners as well.",
    },

    {
        item_name: "Tampons",
        row_order: 39,
        quantity_for_2: "2 packs per person",
        notes_for_2: "If required. Add panty liners as well.",
        quantity_for_3: "2 packs per person",
        notes_for_3: "If required. Add panty liners as well.",
        quantity_for_4: "2 packs per person",
        notes_for_4: "If required. Add panty liners as well.",
        quantity_for_5: "2 packs per person",
        notes_for_5: "If required. Add panty liners as well.",
        quantity_for_6: "2 packs per person",
        notes_for_6: "If required. Add panty liners as well.",
        quantity_for_7: "2 packs per person",
        notes_for_7: "If required. Add panty liners as well.",
        quantity_for_8: "2 packs per person",
        notes_for_8: "If required. Add panty liners as well.",
        quantity_for_9: "2 packs per person",
        notes_for_9: "If required. Add panty liners as well.",
        quantity_for_10: "2 packs per person",
        notes_for_10: "If required. Add panty liners as well.",
    },

    {
        item_name: "Toilet Roll",
        row_order: 40,
        quantity_for_1: "1",
        quantity_for_2: "1",
        quantity_for_3: "2",
        quantity_for_4: "2",
        quantity_for_5: "2",
        quantity_for_6: "3",
        quantity_for_7: "3",
        quantity_for_8: "3",
        quantity_for_9: "3",
        quantity_for_10: "3",
    },

    {
        item_name: "Easter choc treat",
        row_order: 41,
        quantity_for_1: "1",
        notes_for_1: "Find at end of packing tables",
        quantity_for_2: "2",
        notes_for_2: "Find at end of packing tables",
        quantity_for_3: "3",
        notes_for_3: "Find at end of packing tables",
        quantity_for_4: "4",
        notes_for_4: "Find at end of packing tables",
        quantity_for_5: "5",
        notes_for_5: "Find at end of packing tables",
        quantity_for_6: "6",
        notes_for_6: "Find at end of packing tables",
        quantity_for_7: "7",
        notes_for_7: "Find at end of packing tables",
        quantity_for_8: "8",
        notes_for_8: "Find at end of packing tables",
        quantity_for_9: "9",
        notes_for_9: "Find at end of packing tables",
        quantity_for_10: "10",
        notes_for_10: "Find at end of packing tables",
    },
];

export const listsSeedRequired: SnapletListRequired[] = listsSeed.map((list) =>
    snapletListToRequired(list)
);
