name: Checks
on:
  pull_request:
  merge_group:
  push:
    branches:
      - dev
      - main
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install npm
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Remove irrelevant files that may cause TypeScript errors
        run:
          rm -f ./supabase/seed/seed.ts

      - name: Run linting
        run: npm run lint:ci

  verify-database-types:
    name: Verify generated database types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: 1.153.4

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local --schema public > src/databaseTypesFile.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/databaseTypesFile.ts; then
            echo "databaseTypesFile.ts does not match that generated by the local database. See status below:"
            git diff
            exit 1
          fi

  tests:
    name: Tests
    needs:
      - lint
      - verify-database-types
    uses: ./.github/workflows/tests.yml
    secrets: inherit
