env:
  NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
  NEXT_PUBLIC_CYPRESS_TEST_USER: ${{secrets.NEXT_PUBLIC_CYPRESS_TEST_USER}}
  NEXT_PUBLIC_CYPRESS_TEST_PASS: ${{secrets.NEXT_PUBLIC_CYPRESS_TEST_PASS}}

name: Checks
on:
  pull_request:
  push:
    branches:
      main
jobs:
  linting:
    name: Check linting and run component tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install npm
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run component tests
        run: npm run test:component

  e2e_tests:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install npm
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
          retention-days: 1

      - name: Upload Videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: videos
          path: cypress/videos
          retention-days: 1
