name: Deploy database
on:
  workflow_dispatch:
  push:
    paths:
      supabase/migrations/**.sql
    branches:
      main

jobs:
  deploy-dev-database:
    name: Deploy to dev database
    runs-on: ubuntu-latest
    env:
      SUPABASE_DEV_PROJECT_ID: ${{ secrets.SUPABASE_DEV_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DEV_DATABASE_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_DEV_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Link to the project
        run: npx supabase link --project-ref $SUPABASE_DEV_PROJECT_ID
      - name: Dry run the migration
        run: npx supabase db push --dry-run
      - name: Apply the migration
        run: npx supabase db push

  deploy-prod-database:
    name: Deploy to prod database
    environment: prod
    runs-on: ubuntu-latest
    env:
      SUPABASE_PROD_PROJECT_ID: ${{ secrets.SUPABASE_PROD_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PROD_DATABASE_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PROD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Link to the project
        run: npx supabase link --project-ref $SUPABASE_PROD_PROJECT_ID
      - name: Dry run the migration
        run: npx supabase db push --dry-run
      - name: Apply the migration
        run: npx supabase db push

  reset-dev-database-data:
    name: Reset data in dev database
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      SUPABASE_DEV_PROJECT_ID: ${{ secrets.SUPABASE_DEV_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DEV_DATABASE_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_DEV_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Link to the project
        run: npx supabase link --project-ref $SUPABASE_DEV_PROJECT_ID
      - name: Reset data in database
        run: npx supabase db reset --linked

  reset-prod-database-data:
    name: Reset data in prod database
    if: github.event_name == 'workflow_dispatch'
    environment: prod
    runs-on: ubuntu-latest
    env:
      SUPABASE_PROD_PROJECT_ID: ${{ secrets.SUPABASE_PROD_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PROD_DATABASE_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PROD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Link to the project
        run: npx supabase link --project-ref $SUPABASE_PROD_PROJECT_ID
      - name: Reset data in database
        run: npx supabase db reset --linked
