name: Deploy production database
on:
  push:
    branches:
      - production

env:
  SUPABASE_PRODUCTION_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DATABASE_PASSWORD }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PRODUCTION_ACCESS_TOKEN }}

jobs:
  deploy-production-database:
    name: Deploy production database
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Link to the project
        run: npx supabase link --project-ref $SUPABASE_PRODUCTION_PROJECT_ID
      - name: Apply the migration
        run: npx supabase db push --include-all
