name: Dump prod database every hour

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

env:
  SUPABASE_PROD_PROJECT_ID: ${{ secrets.SUPABASE_PROD_PROJECT_ID }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PROD_DATABASE_PASSWORD }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PROD_ACCESS_TOKEN }}

jobs:
  dump-prod-database:
    name: Dump prod database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Link to the project
        run: npx supabase link --project-ref $SUPABASE_PROD_PROJECT_ID

      - name: Create db-backup folder
        run: mkdir db-backup

      - name: Dump schema
        run: npx supabase db dump -f db-backup/schema.sql

      - name: Dump roles
        run: npx supabase db dump --role-only -f db-backup/role.sql

      - name: Dump data
        run: npx supabase db dump --data-only -f db-backup/data.sql

      - name: Save files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: db-backup
